[env:esp32dev]
platform = espressif32 @ 7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 115200
lib_deps = olikraus/U8g2 @ 2.36.12
upload_port = /dev/cu.usbserial-1
monitor_port = /dev/cu.usbserial-1