[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    adafruit/Adafruit SHTC3 Library @ ^1.0.1

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=3

upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
upload_speed = 115200
