; ============================================================
; WeatherStation
; ESP32 Weather Sensor Node
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/generate_build_info.py

lib_deps =
    knolleary/PubSubClient @ ^2.8
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit BME280 Library @ ^2.3.0
    adafruit/Adafruit SHT4x Library @ ^1.0.5

; ------------------------------------------------------------
; Serial Monitor
; ------------------------------------------------------------

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0
; ------------------------------------------------------------
; Build
; ------------------------------------------------------------

build_flags =
    -DCORE_DEBUG_LEVEL=3

; ------------------------------------------------------------
; Upload
; ------------------------------------------------------------
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
upload_speed = 115200
