; ============================================================
; WeatherStation
; ESP32 Weather Sensor Node
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; ------------------------------------------------------------
; Serial Monitor
; ------------------------------------------------------------

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; ------------------------------------------------------------
; Build
; ------------------------------------------------------------

build_flags =
    -DCORE_DEBUG_LEVEL=3

; ------------------------------------------------------------
; Upload
; ------------------------------------------------------------

upload_speed = 921600